/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.au5tie.hireme;

import org.junit.Test;
import static org.junit.Assert.*;

public class FileEvaluatorTest {
    @Test public void testAppHasAGreeting() {
        FileEvaluator classUnderTest = new FileEvaluator();
        assertNotNull("app should have a greeting", "ff");
    }
}
